<?php
    /* @author BRUNO MENDES PIMENTA
    * ESSE CONTROLADOR É RESPONSÁVEL POR FORMAR A PÁGINA
    * DE DEVOLUÇÃO DE MATERIAIS EMPRESTADOS.
    * ELE FAZ A CONEXÃO DAS VIEWS COM AS MODELS
    */

?>